// https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// Kotlin Immutable Collections
kotlinx.collections.immutable.*

kotlin.uuid.*
kotlin.time.*

// Java Time
java.time.*

io.github.king0929zion.zchat.data.model.Conversation
io.github.king0929zion.zchat.data.model.MessageNode
io.github.king0929zion.zchat.ai.ui.UIMessage
io.github.king0929zion.zchat.ai.ui.UIMessageChoice
io.github.king0929zion.zchat.ai.ui.MessageChunk
io.github.king0929zion.zchat.ai.ui.UIMessageAnnotation
io.github.king0929zion.zchat.ai.ui.ToolApprovalState
io.github.king0929zion.zchat.ai.core.TokenUsage